"""add assignment association table

Revision ID: 3e028a545bcc
Revises: d49c6b10ed70
Create Date: 2023-11-14 17:39:00.156097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e028a545bcc'
down_revision = 'd49c6b10ed70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_assignments_project_id_projects'), 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignments_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
